image: registry.gitlab.com/cyber-dojo/version-reporter:v1

stages:
  - pre
  - build
  - test

variables:
  KOSLI_DRY_RUN: "False"
  KOSLI_ORG: cyber-dojo
  KOSLI_FLOW: version-reporter

create-kosli-flow:
  stage: .pre
  script:
    - kosli create flow $KOSLI_FLOW 
            --api-token=$KOSLI_API_TOKEN
            --description="UX for git+image version-reporter" 
            --template=artifact,branch-coverage,snyk-scan

build-job:
  services:
    - docker:dind
  stage: build
  script:
    - source ./sh/echo_versioner_env_vars.sh
    - export $(echo_versioner_env_vars)
    - docker-compose build --build-arg COMMIT_SHA=$CI_COMMIT_SHA
    - TAG=$(echo $CI_COMMIT_SHA | cut -c1-7)
    # DOCKER_USER, DOCKER_PASS secrets
    # echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
    # docker push cyberdojo/version-reporter:$TAG
    # ./sh/install_kosli.sh
    # kosli report artifact cyberdojo/version-reporter:$TAG --artifact-type=docker

test-job:
  stage: test
  script:
    - echo Hello
