variables:
  KOSLI_DRY_RUN: "False"
  KOSLI_CLI_VERSION: "2.6.12"
  KOSLI_HOST: "https://app.kosli.com"
  KOSLI_ORG: cyber-dojo
  KOSLI_FLOW: version-reporter

create-kosli-flow:
  stage: .pre
  script:
    - ./sh/install_kosli.sh
    - kosli create flow $KOSLI_FLOW 
            --api-token=$KOSLI_API_TOKEN
            --description="UX for git+image version-reporter" 
            --template=artifact,branch-coverage,snyk-scan

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
