stages:
  - triggers

trigger_prod:
  stage: triggers
  trigger:
    include: .gitlab/workflows/prod.yml
    strategy: depend

trigger_staging:
  stage: triggers
  trigger:
    include: .gitlab/workflows/staging.yml
    strategy: depend
