variables:
  KOSLI_DRY_RUN: "False"
  KOSLI_HOST: "https://app.kosli.com"
  KOSLI_ORG: cyber-dojo
  KOSLI_API_TOKEN: not-the-api-token
  KOSLI_FLOW: version-reporter

create-kosli-flow:
  stage: .pre
  script:
    - whoami
    - sh -c 'echo "deb [trusted=yes] https://apt.fury.io/kosli/ /"  > /etc/apt/sources.list.d/fury.list'
      # On a clean debian container/machine, you need ca-certificates
    - apt install ca-certificates
    - apt update
    - apt install kosli
      # Verify kosli installation worked
    - kosli version
    - kosli create flow ${KOSLI_FLOW } 
            --description="UX for git+image version-reporter" 
            --template=artifact,branch-coverage,snyk-scan

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
