
create-kosli-flow:
  stage: setup
  script:
    - sudo sh -c 'echo "deb [trusted=yes] https://apt.fury.io/kosli/ /"  > /etc/apt/sources.list.d/fury.list'
      # On a clean debian container/machine, you need ca-certificates
    - sudo apt install ca-certificates
    - sudo apt update
    - sudo apt install kosli
      # Verify kosli installation worked
    - kosli version
    - kosli create flow ${{ env.KOSLI_FLOW }} 
            --description="UX for git+image version-reporter" 
            --template=artifact,branch-coverage,snyk-scan

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
