
version: '3.7'

services:

  shas:
    image: ${CYBER_DOJO_SHAS_IMAGE}:${CYBER_DOJO_SHAS_TAG}
    user: ${CYBER_DOJO_SHAS_SERVER_USER}
    container_name: ${CYBER_DOJO_SHAS_SERVER_CONTAINER_NAME}
    ports: [ "${CYBER_DOJO_SHAS_PORT}:${CYBER_DOJO_SHAS_PORT}" ]
    build:
      context: .
      args: [ COMMIT_SHA ]
    env_file: [ .env ]
    read_only: true
    restart: "no"
    volumes:
      - "./test:/test/:ro"
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -

  nginx:
    image: cyberdojo/nginx-shas-stub
    build:
      context: test/nginx_stub
    init: true
    ports: [ "${CYBER_DOJO_NGINX_PORT}:${CYBER_DOJO_NGINX_PORT}" ]
    user: root

  selenium:
    image: selenium/standalone-firefox
    ports: [ "4444:4444" ]

  client:
    image: ${CYBER_DOJO_SHAS_CLIENT_IMAGE}:${CYBER_DOJO_SHAS_TAG}
    user: ${CYBER_DOJO_SHAS_CLIENT_USER}
    container_name: ${CYBER_DOJO_SHAS_CLIENT_CONTAINER_NAME}
    ports: [ "${CYBER_DOJO_SHAS_CLIENT_PORT}:${CYBER_DOJO_SHAS_CLIENT_PORT}" ]
    build:
      context: test/client
      args: [ COMMIT_SHA ]
    depends_on:
      - nginx
      - shas
      - selenium
    env_file: [ .env ]
    read_only: true
    restart: "no"
    volumes:
      - "./test:/test/:ro"
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB

